// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcssximmkrrzfsbcnigz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjc3N4aW1ta3JyemZzYmNuaWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDM5MTQsImV4cCI6MjA3MDY3OTkxNH0.CZOAVuosOqZ0YvCJsTppvmdIpJCV2lawous_5SudVEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});